import Phaser from 'phaser';

import { AutoPlayer } from '../auto/AutoPlayer';
import { BossAttackController } from '../boss/BossAttackController';
import { CharacterRuntime } from '../character/CharacterRuntime';
import { BossSpawnDirector } from '../boss/BossSpawnDirector';
import { DamageCalculator } from '../combat/DamageCalculator';
import { EventBus } from '../core/EventBus';
import type { GameEventMap } from '../core/domain/GameEvents';
import { TimeManager } from '../core/TimeManager';
import { BossController } from '../enemy/BossController';
import { Enemy } from '../enemy/Enemy';
import { EnemyFactory } from '../enemy/EnemyFactory';
import { EnemyFlow } from '../enemy/EnemyFlow';
import { EnemyMovement } from '../enemy/EnemyMovement';
import { EndlessBossManager } from '../endless/EndlessBossManager';
import { EndlessManager } from '../endless/EndlessManager';
import { GameEventBridge } from '../events/GameEventBridge';
import { GameEventBus } from '../events/GameEventBus';
import { GameEventRecorder } from '../events/GameEventRecorder';
import { EvolutionManager } from '../evolution/EvolutionManager';
import { VirtualJoystick } from '../input/VirtualJoystick';
import { MapMechanicRuntime } from '../map/mechanics/MapMechanicRuntime';
import { PickupManager } from '../pickup/PickupManager';
import { PerformanceMonitor } from '../performance/PerformanceMonitor';
import { PoolManager } from '../performance/PoolManager';
import { TreasureManager } from '../pickup/TreasureManager';
import { PassiveManager } from '../passive/PassiveManager';
import { PlayerController } from '../player/PlayerController';
import { PlayerHealth } from '../player/PlayerHealth';
import { PlayerState } from '../player/PlayerState';
import { PlayerStats } from '../player/PlayerStats';
import { RandomManager } from '../random/RandomManager';
import { RelicManager } from '../relic/RelicManager';
import { ReplayRecorder } from '../replay/ReplayRecorder';
import { ExpManager } from '../progression/ExpManager';
import { LevelManager } from '../progression/LevelManager';
import { UpgradeApplier } from '../progression/UpgradeApplier';
import { UpgradeFlow } from '../progression/UpgradeFlow';
import { UpgradeSelector } from '../progression/UpgradeSelector';
import { RunState } from '../run/RunState';
import { RunRuleSet } from '../rules/RunRuleSet';
import { PlaytestSettingsState } from '../settings/PlaytestSettings';
import { SpawnDirector } from '../spawn/SpawnDirector';
import { RunStats } from '../stats/RunStats';
import { RuntimeStrategyState } from '../strategy/runtime/RuntimeStrategyState';
import { FloatingTextManager } from '../ui/FloatingTextManager';
import { WeaponManager } from '../weapon/WeaponManager';

export interface GameplayContext {
  scene: Phaser.Scene;
  runId: string;
  playtestSettings: PlaytestSettingsState;
  autoMode: boolean;
  autoMovementEnabled: boolean;
  autoUpgradeEnabled: boolean;
  runtimeStrategyState?: RuntimeStrategyState;
  fastMode: boolean;
  endlessMode: boolean;
  timeScale: number;
  effectiveTimeScale: number;
  eventBus: EventBus<GameEventMap>;
  gameEventBus: GameEventBus;
  gameEventRecorder?: GameEventRecorder;
  gameEventBridge?: GameEventBridge;
  autoPlayer: AutoPlayer;
  damageCalculator: DamageCalculator;
  enemyMovement: EnemyMovement;
  timeManager: TimeManager;
  randomManager: RandomManager;
  performanceMonitor: PerformanceMonitor;
  poolManager: PoolManager;
  runSeed: string;
  replayRecorder?: ReplayRecorder;
  runRuleSet: RunRuleSet;
  relicManager: RelicManager;
  mapMechanicRuntime: MapMechanicRuntime;
  characterRuntime: CharacterRuntime;
  syncCharacterCombatModifiers(): void;
  runState: RunState;
  runStats: RunStats;
  player: PlayerController;
  playerState: PlayerState;
  playerStats: PlayerStats;
  playerHealth: PlayerHealth;
  playerPickupRange: number;
  enemies: Enemy[];
  enemyFlow: EnemyFlow;
  bossController: BossController;
  endlessManager: EndlessManager;
  endlessBossManager: EndlessBossManager;
  enemyFactory: EnemyFactory;
  weaponManager: WeaponManager;
  pickupManager: PickupManager;
  treasureManager: TreasureManager;
  evolutionManager: EvolutionManager;
  passiveManager: PassiveManager;
  expManager: ExpManager;
  levelManager: LevelManager;
  expRequirementMultiplier: number;
  upgradeSelector: UpgradeSelector;
  upgradeApplier: UpgradeApplier;
  upgradeFlow: UpgradeFlow;
  spawnDirector: SpawnDirector;
  bossSpawnDirector: BossSpawnDirector;
  bossAttackController?: BossAttackController;
  floatingTextManager: FloatingTextManager;
  virtualJoystick: VirtualJoystick;
}
