export type GameEventType =
  | 'run.started'
  | 'run.ended'
  | 'player.damageTaken'
  | 'player.healed'
  | 'player.shieldGained'
  | 'player.shieldConsumed'
  | 'player.levelUp'
  | 'enemy.spawned'
  | 'enemy.damaged'
  | 'enemy.killed'
  | 'boss.spawned'
  | 'boss.killed'
  | 'boss.skillUsed'
  | 'boss.skillHit'
  | 'endless.started'
  | 'endless.rewardChosen'
  | 'endless.bossSpawned'
  | 'endless.bossKilled'
  | 'pickup.expCollected'
  | 'pickup.treasureDropped'
  | 'pickup.treasureOpened'
  | 'upgrade.optionsShown'
  | 'upgrade.selected'
  | 'upgrade.applied'
  | 'upgrade.skipped'
  | 'weapon.added'
  | 'weapon.upgraded'
  | 'weapon.evolved'
  | 'weapon.hit'
  | 'passive.added'
  | 'passive.upgraded'
  | 'ui.pauseOpened'
  | 'ui.pauseClosed'
  | 'ui.settingsChanged';

export type AnyGameEventType = GameEventType | string;
