export const MINIMAP_STYLE = {
  terrain: {
    riverColor: 0x155e63,
    riverAlpha: 0.22,
    riverStrokeAlpha: 0.3,
    swampColor: 0x365f3f,
    swampAlpha: 0.2,
    swampStrokeAlpha: 0.28,
    mudColor: 0x5a3e1f,
    mudAlpha: 0.2,
    mudStrokeAlpha: 0.28,
    obstacleColor: 0x475569,
    obstacleAlpha: 0.3,
    lightRadiusColor: 0xfacc15,
    lightRadiusAlpha: 0.1,
  },
  icons: {
    slowZoneAlpha: 0.42,
    portalAlpha: 0.72,
    lightAlpha: 0.48,
    obstacleAlpha: 0.5,
    hazardAlpha: 0.68,
    defaultAlpha: 0.58,
  },
  markers: {
    playerCenterColor: 0xfacc15,
    playerCenterRadius: 3,
    playerOutlineRadius: 4,
    playerRingRadius: 5,
    bossCenterRadius: 4,
    bossRingRadius: 6,
    finalBossCenterRadius: 4.5,
    finalBossRingRadius: 7,
  },
} as const;
