import type { BossAttackController } from '../boss/BossAttackController';
import type { BossSpawnDirector } from '../boss/BossSpawnDirector';
import { EventBus } from '../core/EventBus';
import type { Enemy, GameEventMap } from '../enemy/Enemy';
import type { EnemyFactory } from '../enemy/EnemyFactory';
import type { EndlessBossManager } from '../endless/EndlessBossManager';
import type { EndlessManager } from '../endless/EndlessManager';
import type { EvolutionManager } from '../evolution/EvolutionManager';
import type { VirtualJoystick } from '../input/VirtualJoystick';
import { PlaytestLog } from '../logging/PlaytestLog';
import type { PassiveManager } from '../passive/PassiveManager';
import type { PickupManager } from '../pickup/PickupManager';
import type { TreasureManager } from '../pickup/TreasureManager';
import type { PlayerController } from '../player/PlayerController';
import type { PlayerHealth } from '../player/PlayerHealth';
import type { PlayerStats } from '../player/PlayerStats';
import type { ExpManager } from '../progression/ExpManager';
import type { LevelManager } from '../progression/LevelManager';
import type { UpgradeApplier } from '../progression/UpgradeApplier';
import type { UpgradeFlow } from '../progression/UpgradeFlow';
import { PlaytestSettings, type PlaytestSettingsState } from '../settings/PlaytestSettings';
import { SettingsManager } from '../settings/SettingsManager';
import type { SpawnDirector } from '../spawn/SpawnDirector';
import type { FloatingTextManager } from '../ui/FloatingTextManager';
import type { WeaponManager } from '../weapon/WeaponManager';

export interface GameSceneRunResetScenePort {
  eventBus: EventBus<GameEventMap>;
  enemies: Enemy[];
  contactDamageCooldowns: Map<Enemy, number>;
  timeManager: { reset(): void };
  centerMessageController: { clear(): void };
  unsubscribeLevelUp?: () => void;
  unsubscribeEnemyKilled?: () => void;
  unsubscribeSettings?: () => void;
  playtestSettings: PlaytestSettingsState;
  runState: { reset(): void };
  runId: string;
  runtimeStrategyProfileSynchronizer: { clear(): void };
  player?: PlayerController;
  playerHealth?: PlayerHealth;
  expManager?: ExpManager;
  levelManager?: LevelManager;
  playerStats?: PlayerStats;
  upgradeApplier?: UpgradeApplier;
  upgradeFlow?: UpgradeFlow;
  isGameplayPaused: boolean;
  liveStrategyControlHandler: { reset(): void };
  strategyTacticsPanelEnabledForRun: boolean;
  upgradeSelectionState: { clear(): void };
  isPauseMenuOpen: boolean;
  isGameOver: boolean;
  spawnDirector?: SpawnDirector;
  bossSpawnDirector?: BossSpawnDirector;
  bossAttackController?: BossAttackController;
  endlessManager?: EndlessManager;
  endlessBossManager?: EndlessBossManager;
  enemyFactory?: EnemyFactory;
  floatingTextManager?: FloatingTextManager;
  enemyDamageFeedbackController: { clear(): void };
  playerFeedbackController: { clear(): void };
  treasureRewardFeedbackController: { clear(): void };
  virtualJoystick?: VirtualJoystick;
  weaponManager?: WeaponManager;
  pickupManager?: PickupManager;
  treasureManager?: TreasureManager;
  evolutionManager?: EvolutionManager;
  passiveManager?: PassiveManager;
}

export class GameSceneRunResetAdapter {
  reset(scene: GameSceneRunResetScenePort): void {
    SettingsManager.clearVisualRestartRequired();
    scene.enemies = [];
    scene.contactDamageCooldowns.clear();
    scene.timeManager.reset();
    scene.centerMessageController.clear();
    scene.eventBus = new EventBus<GameEventMap>();
    scene.unsubscribeLevelUp = undefined;
    scene.unsubscribeEnemyKilled = undefined;
    scene.unsubscribeSettings?.();
    scene.unsubscribeSettings = undefined;
    scene.playtestSettings = PlaytestSettings.get();
    scene.runState.reset();
    scene.runId = PlaytestLog.createRunId();
    scene.runtimeStrategyProfileSynchronizer.clear();
    scene.player = undefined;
    scene.playerHealth = undefined;
    scene.expManager = undefined;
    scene.levelManager = undefined;
    scene.playerStats = undefined;
    scene.upgradeApplier = undefined;
    scene.upgradeFlow = undefined;
    scene.isGameplayPaused = false;
    scene.liveStrategyControlHandler.reset();
    scene.strategyTacticsPanelEnabledForRun =
      SettingsManager.getGameplay().showStrategyTacticsPanel === true;
    scene.upgradeSelectionState.clear();
    scene.isPauseMenuOpen = false;
    scene.isGameOver = false;
    scene.spawnDirector = undefined;
    scene.bossSpawnDirector = undefined;
    scene.bossAttackController = undefined;
    scene.endlessManager = undefined;
    scene.endlessBossManager = undefined;
    scene.enemyFactory = undefined;
    scene.floatingTextManager = undefined;
    scene.enemyDamageFeedbackController.clear();
    scene.playerFeedbackController.clear();
    scene.treasureRewardFeedbackController.clear();
    scene.virtualJoystick = undefined;
    scene.weaponManager = undefined;
    scene.pickupManager = undefined;
    scene.treasureManager = undefined;
    scene.evolutionManager = undefined;
    scene.passiveManager = undefined;
  }
}
