from __future__ import annotations

import json
import math
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Callable

from PIL import Image, ImageDraw, ImageFilter, ImageFont


ROOT = Path(__file__).resolve().parents[1]
ART_ROOT = ROOT / "public" / "assets" / "art"
MANIFEST_PATH = ART_ROOT / "animation_manifest.json"
TMP_ROOT = ROOT / "tmp" / "premium_pixel_art"

DIRECTIONS = [
    "up",
    "up_right",
    "right",
    "down_right",
    "down",
    "down_left",
    "left",
    "up_left",
]

WEAPON_IDS = [
    "knife",
    "garlic",
    "bible",
    "magic_wand",
    "axe",
    "thousand_edge",
    "holy_wand",
    "death_spiral",
    "unholy_vespers",
    "soul_eater",
]

PASSIVE_IDS = ["spinach", "empty_tome", "bracer", "clover", "pummarola"]

EXTRA_MANIFEST_ASSETS = [
    ("map-mechanics/altar/cathedral_altar.png", "art_map_mechanics_cathedral_altar", "image", 160, 160, 1),
    ("map-mechanics/altar/cathedral_altar_minimap.png", "art_map_mechanics_cathedral_altar_minimap", "image", 32, 32, 1),
    ("map-mechanics/light/cathedral_candle.png", "art_map_mechanics_cathedral_candle", "image", 128, 128, 1),
    ("map-mechanics/obstacle/cathedral_pillar.png", "art_map_mechanics_cathedral_pillar", "image", 128, 128, 1),
    ("map-mechanics/obstacle/cathedral_wall.png", "art_map_mechanics_cathedral_wall", "image", 128, 128, 1),
    ("map-mechanics/portal/portal_gold.png", "art_map_mechanics_portal_gold", "image", 128, 128, 1),
    ("map-mechanics/portal/portal_minimap_gold.png", "art_map_mechanics_portal_minimap_gold", "image", 32, 32, 1),
    ("world/cathedral_ground_tile.png", "art_world_cathedral_ground_tile", "image", 128, 128, 1),
]

PALETTES = {
    "assassin_default": {
        "cloth": (47, 48, 94, 255),
        "trim": (139, 92, 246, 255),
        "hair": (28, 24, 44, 255),
        "skin": (232, 190, 144, 255),
        "metal": (174, 190, 212, 255),
    },
    "witch_default": {
        "cloth": (70, 48, 112, 255),
        "trim": (244, 114, 182, 255),
        "hair": (240, 232, 180, 255),
        "skin": (237, 190, 164, 255),
        "metal": (150, 211, 255, 255),
    },
    "priest_default": {
        "cloth": (226, 222, 198, 255),
        "trim": (96, 165, 250, 255),
        "hair": (96, 75, 56, 255),
        "skin": (226, 178, 136, 255),
        "metal": (250, 204, 21, 255),
    },
    "warrior_default": {
        "cloth": (119, 47, 45, 255),
        "trim": (248, 113, 113, 255),
        "hair": (79, 70, 64, 255),
        "skin": (226, 176, 128, 255),
        "metal": (172, 190, 210, 255),
    },
}


@dataclass(frozen=True)
class Asset:
    path: str
    key: str
    type: str
    frame_width: int
    frame_height: int
    frames: int
    raw: dict[str, Any]


def main() -> None:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assets = [parse_asset(raw) for raw in manifest["assets"]]
    assets = merge_assets([
        *assets,
        *(make_asset(*extra) for extra in EXTRA_MANIFEST_ASSETS),
    ])
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_dir = TMP_ROOT / "backups" / stamp / "art"
    review_dir = TMP_ROOT / "review" / stamp
    backup_art(backup_dir)

    generated_assets: list[Asset] = []
    for asset in assets:
        out_path = ART_ROOT / asset.path
        out_path.parent.mkdir(parents=True, exist_ok=True)
        image = render_asset(asset)
        image.save(out_path)
        generated_assets.append(asset)

    tier_assets = generate_tier_assets()
    for tier_asset in tier_assets:
        generated_assets.append(tier_asset)

    manifest["style"] = "Premium high-definition pixel art, readable top-down action RPG sprites, distinct upgrade tiers"
    manifest["version"] = f"premium-pixel-full-regen-{stamp}"
    manifest["notes"] = [
        "Generated by scripts/generate-premium-pixel-art.py.",
        "Transparent RGBA PNGs are used for characters, objects, weapons, effects, and UI overlays.",
        "World tiles intentionally fill the full canvas for seamless map rendering.",
        "Weapon and passive tier variants use visibly stronger silhouette, color, glow, and ornamentation per tier.",
        "Review output includes a tier progression sheet for side-by-side level readability checks.",
    ]
    manifest["assets"] = [asset.raw for asset in merge_assets(generated_assets)]
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    render_review_sheets(review_dir, merge_assets(generated_assets))
    render_tier_progression_review(review_dir)
    print(f"backup={backup_dir}")
    print(f"review={review_dir}")
    print(f"assets={len(merge_assets(generated_assets))}")


def parse_asset(raw: dict[str, Any]) -> Asset:
    return Asset(
        path=raw["path"],
        key=raw["key"],
        type=raw["type"],
        frame_width=int(raw["frameWidth"]),
        frame_height=int(raw["frameHeight"]),
        frames=int(raw["frames"]),
        raw=dict(raw),
    )


def backup_art(backup_dir: Path) -> None:
    if backup_dir.exists():
        shutil.rmtree(backup_dir)
    shutil.copytree(ART_ROOT, backup_dir, ignore=shutil.ignore_patterns("animation_manifest.json"))
    backup_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(MANIFEST_PATH, backup_dir / "animation_manifest.json")


def merge_assets(assets: list[Asset]) -> list[Asset]:
    by_key: dict[str, Asset] = {}
    for asset in assets:
        by_key[asset.key] = asset
    return list(by_key.values())


def image_size_for(asset: Asset) -> tuple[int, int]:
    current = ART_ROOT / asset.path
    if current.exists():
        try:
            with Image.open(current) as image:
                return image.size
        except Exception:
            pass

    if asset.type == "spritesheet":
        if asset.raw.get("rows") and asset.raw.get("columns"):
            return asset.frame_width * int(asset.raw["columns"]), asset.frame_height * int(asset.raw["rows"])
        return asset.frame_width * asset.frames, asset.frame_height
    return asset.frame_width, asset.frame_height


def render_asset(asset: Asset) -> Image.Image:
    path = asset.path.replace("\\", "/")
    if path.startswith("player/"):
        return render_player_asset(asset)
    if path.startswith("weapons/"):
        return render_weapon_asset(asset, tier=1)
    if path.startswith("passives/"):
        return render_passive_asset(asset, tier=1)
    if path.startswith("enemies/"):
        return render_enemy_asset(asset)
    if path.startswith("effects/"):
        return render_effect_asset(asset, tier=1)
    if path.startswith("pickups/"):
        return render_pickup_asset(asset)
    if path.startswith("ui/"):
        return render_ui_asset(asset)
    if path.startswith("world/"):
        return render_world_asset(asset)
    if path.startswith("map-mechanics/"):
        return render_map_mechanic_asset(asset)
    return transparent_canvas(*image_size_for(asset))


def render_player_asset(asset: Asset) -> Image.Image:
    path = asset.path.replace("\\", "/")
    parts = path.split("/")
    size = image_size_for(asset)

    if len(parts) >= 3 and parts[1] in PALETTES:
        skin = parts[1]
        name = parts[-1]
        if name.startswith("walk_") and name != "walk_8dir_sheet.png":
            direction = name.removeprefix("walk_").removesuffix(".png")
            return render_player_strip(skin, "walk", direction)
        if name.startswith("idle_"):
            direction = name.removeprefix("idle_").removesuffix(".png")
            return render_player_strip(skin, "idle", direction)
        if name == "walk_8dir_sheet.png":
            return stack_direction_sheets([render_player_strip(skin, "walk", direction) for direction in DIRECTIONS])
        if name == "idle_8dir_sheet.png":
            return stack_direction_sheets([render_player_strip(skin, "idle", direction) for direction in DIRECTIONS])
        if name == "portrait.png":
            return render_portrait(skin)
        if name == "hit_fx.png":
            return render_burst(size[0], size[1], PALETTES[skin]["trim"], rings=3)
        if name in ("blink_trail.png", "blink_flash.png", "slow_zone.png", "sanctuary_circle.png", "counter_wave.png"):
            return render_skill_effect(size[0], size[1], PALETTES[skin]["trim"], name)

    if path.endswith("_walk_sheet.png") or path.endswith("player_walk_sheet.png"):
        skin = next((skin_id for skin_id in PALETTES if skin_id in path), "assassin_default")
        return render_player_strip(skin, "walk", "down")

    return transparent_canvas(*size)


def render_player_strip(skin: str, state: str, direction: str) -> Image.Image:
    sheet = transparent_canvas(320, 80)
    for frame in range(4):
        cell = transparent_canvas(80, 80)
        draw_player_frame(cell, skin, state, direction, frame)
        sheet.alpha_composite(cell, (frame * 80, 0))
    return sheet


def draw_player_frame(image: Image.Image, skin: str, state: str, direction: str, frame: int) -> None:
    draw = ImageDraw.Draw(image, "RGBA")
    p = PALETTES[skin]
    bob = 0 if state == "idle" else [0, -2, 0, -1][frame]
    step = [-3, 2, 3, -2][frame] if state == "walk" else [0, 1, 0, -1][frame]
    cx = 40
    feet_y = 74
    body_y = 43 + bob
    dx = direction_dx(direction)
    dy = direction_dy(direction)

    draw.ellipse((22, 67, 58, 77), fill=(0, 0, 0, 70))
    draw.ellipse((25, 69, 55, 75), fill=(0, 0, 0, 50))
    cape_color = add_alpha(shade(p["cloth"], -42), 220)
    if dy <= 0:
        draw.polygon(
            [
                (28 - dx * 3, body_y + 5),
                (52 - dx * 3, body_y + 5),
                (58 - dx * 5, 69 + bob),
                (22 - dx * 5, 69 + bob),
            ],
            fill=cape_color,
            outline=(15, 23, 42, 220),
        )
    draw.line((cx - 10, 56 + bob, cx - 8 + step, feet_y), fill=shade(p["cloth"], -45), width=5)
    draw.line((cx + 10, 56 + bob, cx + 8 - step, feet_y), fill=shade(p["cloth"], -45), width=5)
    draw.line((cx - 18, 42 + bob, cx - 24 - dx * 3, 56 + bob), fill=shade(p["cloth"], -35), width=5)
    draw.line((cx + 18, 42 + bob, cx + 24 - dx * 3, 56 + bob), fill=shade(p["cloth"], -35), width=5)
    rounded(draw, (23, body_y - 2, 57, body_y + 28), 10, outline=(19, 23, 42, 255), fill=shade(p["cloth"], -25))
    rounded(draw, (27, body_y - 6, 53, body_y + 22), 8, outline=(19, 23, 42, 255), fill=p["cloth"])
    draw.rectangle((31, body_y + 4, 49, body_y + 8), fill=p["trim"])
    draw.rectangle((35, body_y - 5, 45, body_y + 23), fill=add_alpha(p["trim"], 160))
    draw.rectangle((29, body_y + 13, 51, body_y + 16), fill=shade(p["metal"], -22))
    draw.rectangle((39, body_y + 11, 44, body_y + 18), fill=shade(p["metal"], 22))
    draw.line((30, body_y, 50, body_y + 21), fill=add_alpha(shade(p["trim"], 48), 110), width=1)
    draw.ellipse((27, 18 + bob, 53, 44 + bob), fill=(19, 23, 42, 255))
    draw.ellipse((30, 20 + bob, 50, 40 + bob), fill=p["skin"])
    draw.pieslice((24, 13 + bob, 56, 37 + bob), 180, 360, fill=p["hair"])
    draw.rectangle((30, 17 + bob, 50, 25 + bob), fill=p["hair"])

    face_x = cx + dx * 5
    if dy >= 0:
        draw.rectangle((face_x - 6, 30 + bob, face_x - 3, 33 + bob), fill=(30, 41, 59, 255))
        draw.rectangle((face_x + 3, 30 + bob, face_x + 6, 33 + bob), fill=(30, 41, 59, 255))
        draw.rectangle((face_x - 3, 36 + bob, face_x + 3, 38 + bob), fill=shade(p["skin"], -35))
    else:
        draw.rectangle((30, 29 + bob, 50, 34 + bob), fill=shade(p["hair"], 12))

    if skin == "warrior_default":
        draw.line((58, 35 + bob, 67 + dx * 2, 55 + bob), fill=p["metal"], width=4)
        draw.rectangle((58, 31 + bob, 63, 38 + bob), fill=shade(p["metal"], 25))
        draw.polygon([(21, 42 + bob), (12, 49 + bob), (20, 58 + bob), (29, 51 + bob)], fill=shade(p["metal"], -5), outline=(51, 65, 85, 255))
        draw.rectangle((33, body_y - 3, 47, body_y + 1), fill=shade(p["metal"], 34))
    elif skin == "assassin_default":
        draw.polygon([(57, 39 + bob), (67, 34 + bob), (61, 46 + bob)], fill=p["metal"])
        draw.polygon([(23, 20 + bob), (33, 11 + bob), (31, 25 + bob)], fill=shade(p["cloth"], -30), outline=(15, 23, 42, 220))
        draw.line((19, 47 + bob, 12, 55 + bob), fill=p["metal"], width=2)
    elif skin == "witch_default":
        draw.polygon([(24, 19 + bob), (40, 2 + bob), (56, 19 + bob)], fill=shade(p["cloth"], -10), outline=(19, 23, 42, 255))
        draw.ellipse((58, 43 + bob, 65, 50 + bob), fill=add_alpha(p["trim"], 230))
        draw.line((61, 47 + bob, 66, 35 + bob), fill=(120, 53, 15, 255), width=2)
        star(draw, 66, 34 + bob, 4, fill=add_alpha(p["trim"], 220), outline=add_alpha((255, 255, 255, 255), 160))
    elif skin == "priest_default":
        draw.ellipse((29, 15 + bob, 51, 25 + bob), outline=add_alpha(p["metal"], 210), width=2)
        draw.rectangle((38, body_y + 3, 42, body_y + 18), fill=p["metal"])
        draw.rectangle((34, body_y + 8, 46, body_y + 12), fill=p["metal"])
        draw.line((26, body_y + 2, 22, body_y + 19), fill=add_alpha(p["trim"], 190), width=2)
        draw.line((54, body_y + 2, 58, body_y + 19), fill=add_alpha(p["trim"], 190), width=2)

    add_highlight(draw, (28, body_y - 4, 52, body_y + 18), p["trim"])
    add_sprite_sparkle(draw, cx + dx * 12, body_y - 8, p["trim"], frame)


def direction_dx(direction: str) -> int:
    return -1 if "left" in direction else 1 if "right" in direction else 0


def direction_dy(direction: str) -> int:
    if direction.startswith("up"):
        return -1
    if direction.startswith("down"):
        return 1
    return 0


def stack_direction_sheets(sheets: list[Image.Image]) -> Image.Image:
    out = transparent_canvas(320, 80 * len(sheets))
    for index, sheet in enumerate(sheets):
        out.alpha_composite(sheet, (0, index * 80))
    return out


def render_portrait(skin: str) -> Image.Image:
    image = transparent_canvas(128, 128)
    draw = ImageDraw.Draw(image, "RGBA")
    p = PALETTES[skin]
    draw.ellipse((18, 92, 110, 120), fill=(0, 0, 0, 80))
    rounded(draw, (28, 50, 100, 122), 20, fill=p["cloth"], outline=(15, 23, 42, 255))
    rounded(draw, (35, 58, 93, 118), 16, fill=shade(p["cloth"], 18), outline=(15, 23, 42, 255))
    draw.ellipse((34, 16, 94, 76), fill=(15, 23, 42, 255))
    draw.ellipse((42, 24, 86, 70), fill=p["skin"])
    draw.pieslice((30, 6, 98, 66), 180, 360, fill=p["hair"])
    draw.rectangle((44, 20, 84, 34), fill=p["hair"])
    draw.rectangle((51, 46, 57, 52), fill=(15, 23, 42, 255))
    draw.rectangle((71, 46, 77, 52), fill=(15, 23, 42, 255))
    draw.rectangle((56, 61, 72, 65), fill=shade(p["skin"], -40))
    draw.rectangle((48, 88, 80, 96), fill=p["trim"])
    draw.ellipse((84, 82, 110, 108), outline=add_alpha(p["trim"], 190), width=4)
    return add_pixel_polish(image)


def render_weapon_asset(asset: Asset, tier: int) -> Image.Image:
    width, height = image_size_for(asset)
    key = asset.key
    weapon = weapon_from_key(key, asset.path)
    if asset.type == "spritesheet":
        sheet = transparent_canvas(width, height)
        for frame in range(asset.frames):
            cell = transparent_canvas(asset.frame_width, asset.frame_height)
            draw_weapon_symbol(cell, weapon, tier, frame, animated=True)
            sheet.alpha_composite(cell, (frame * asset.frame_width, 0))
        return sheet
    image = transparent_canvas(width, height)
    draw_weapon_symbol(image, weapon, tier, 0, animated=False)
    return image


def render_passive_asset(asset: Asset, tier: int) -> Image.Image:
    width, height = image_size_for(asset)
    passive = passive_from_key(asset.key, asset.path)
    image = transparent_canvas(width, height)
    draw_passive_symbol(image, passive, tier)
    return image


def render_enemy_asset(asset: Asset) -> Image.Image:
    width, height = image_size_for(asset)
    enemy = enemy_from_key(asset.key, asset.path)
    if asset.type == "spritesheet":
        sheet = transparent_canvas(width, height)
        for frame in range(asset.frames):
            cell = transparent_canvas(asset.frame_width, asset.frame_height)
            draw_enemy(cell, enemy, frame)
            sheet.alpha_composite(cell, (frame * asset.frame_width, 0))
        return sheet
    image = transparent_canvas(width, height)
    draw_enemy(image, enemy, 0)
    return image


def render_effect_asset(asset: Asset, tier: int) -> Image.Image:
    width, height = image_size_for(asset)
    if asset.type == "spritesheet":
        sheet = transparent_canvas(width, height)
        for frame in range(asset.frames):
            cell = render_burst(asset.frame_width, asset.frame_height, effect_color(asset.key), rings=2 + tier, frame=frame)
            sheet.alpha_composite(cell, (frame * asset.frame_width, 0))
        return sheet
    return render_warning(width, height, effect_color(asset.key))


def render_pickup_asset(asset: Asset) -> Image.Image:
    width, height = image_size_for(asset)
    image = transparent_canvas(width, height)
    draw = ImageDraw.Draw(image, "RGBA")
    if "chest" in asset.key:
        rounded(draw, (8, height * 0.34, width - 8, height - 8), 6, fill=(126, 74, 36, 255), outline=(46, 30, 24, 255))
        draw.rectangle((10, int(height * 0.34), width - 10, int(height * 0.58)), fill=(176, 109, 45, 255))
        draw.rectangle((width // 2 - 6, int(height * 0.42), width // 2 + 6, int(height * 0.70)), fill=(250, 204, 21, 255))
        draw.rectangle((14, int(height * 0.62), width - 14, int(height * 0.70)), fill=(250, 204, 21, 255))
    else:
        draw.polygon([(width // 2, 2), (width - 5, height // 3), (width * 3 // 4, height - 4), (width // 4, height - 4), (5, height // 3)], fill=(56, 189, 248, 255), outline=(219, 234, 254, 255))
        draw.line((width // 2, 2, width // 2, height - 5), fill=(219, 234, 254, 190), width=2)
    return add_pixel_polish(image)


def render_ui_asset(asset: Asset) -> Image.Image:
    width, height = image_size_for(asset)
    image = transparent_canvas(width, height)
    draw = ImageDraw.Draw(image, "RGBA")
    if "panel" in asset.key:
        rounded(draw, (2, 2, width - 3, height - 3), 10, fill=(8, 15, 30, 230), outline=(125, 211, 252, 190))
        rounded(draw, (7, 7, width - 8, height - 8), 7, fill=(15, 23, 42, 210), outline=(51, 65, 85, 180))
        draw.rectangle((12, 10, width - 13, 17), fill=(96, 165, 250, 100))
        draw.rectangle((12, height - 18, width - 13, height - 11), fill=(30, 41, 59, 150))
        for x, y in [(9, 9), (width - 13, 9), (9, height - 13), (width - 13, height - 13)]:
            draw.rectangle((x, y, x + 4, y + 4), fill=(250, 204, 21, 190))
        for x in range(18, width - 18, 18):
            draw.point((x, 13), fill=(226, 232, 240, 120))
    elif "weapon_frame" in asset.key:
        draw_icon_frame(draw, width, height, (59, 130, 246, 255), tier=2)
    elif "passive_frame" in asset.key:
        draw_icon_frame(draw, width, height, (34, 197, 94, 255), tier=2)
    else:
        draw_icon_frame(draw, width, height, (148, 163, 184, 255), tier=1)
        if "hp" in asset.key:
            draw.ellipse((18, 18, width - 18, height - 18), fill=(239, 68, 68, 255))
            draw.rectangle((width // 2 - 5, 20, width // 2 + 5, height - 20), fill=(254, 242, 242, 255))
            draw.rectangle((20, height // 2 - 5, width - 20, height // 2 + 5), fill=(254, 242, 242, 255))
        elif "exp" in asset.key:
            draw.polygon([(width // 2, 12), (width - 14, height // 2), (width // 2, height - 12), (14, height // 2)], fill=(56, 189, 248, 255))
        elif "time" in asset.key:
            draw.ellipse((15, 13, width - 15, height - 11), outline=(226, 232, 240, 255), width=5)
            draw.line((width // 2, height // 2, width // 2, 24), fill=(226, 232, 240, 255), width=4)
            draw.line((width // 2, height // 2, width - 26, height // 2 + 8), fill=(226, 232, 240, 255), width=4)
    return add_pixel_polish(image)


def render_world_asset(asset: Asset) -> Image.Image:
    width, height = image_size_for(asset)
    image = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image, "RGBA")
    key = asset.key
    if "tile" in key:
        base = (52, 65, 52, 255)
        accent = (94, 151, 104, 255)
        if "graveyard" in key:
            base = (70, 68, 58, 255)
            accent = (127, 121, 96, 255)
        elif "swamp" in key:
            base = (35, 72, 63, 255)
            accent = (74, 130, 90, 255)
        elif "ruins" in key:
            base = (77, 82, 87, 255)
            accent = (132, 143, 150, 255)
        elif "cathedral" in key:
            base = (63, 65, 72, 255)
            accent = (202, 169, 82, 255)
        elif "grass" in key:
            base = (45, 91, 61, 255)
            accent = (92, 171, 102, 255)
        draw.rectangle((0, 0, width, height), fill=base)
        if "cathedral" in key:
            for y in range(0, height, 32):
                draw.line((0, y, width, y), fill=shade(base, -24), width=2)
            for x in range(0, width, 32):
                draw.line((x, 0, x, height), fill=shade(base, -24), width=2)
            for x in range(16, width, 32):
                draw.line((x, 0, x, height), fill=add_alpha(accent, 65), width=1)
            for i in range(10):
                x = (i * 47 + 7) % width
                y = (i * 31 + 19) % height
                draw.line((x, y, x + 13, y + 4), fill=add_alpha(shade(accent, 40), 150), width=1)
        elif "ruins" in key:
            for i in range(18):
                x = (i * 23 + 11) % width
                y = (i * 41 + 5) % height
                draw.rectangle((x, y, x + 10, y + 7), outline=add_alpha(shade(accent, -18), 130))
                draw.line((x + 2, y + 7, x + 8, y + 12), fill=add_alpha(shade(base, -35), 160), width=1)
        elif "graveyard" in key:
            for i in range(12):
                x = (i * 29 + 4) % width
                y = (i * 17 + 12) % height
                draw.arc((x, y, x + 16, y + 8), 180, 360, fill=add_alpha(accent, 80), width=1)
        elif "swamp" in key:
            for i in range(12):
                x = (i * 37 + 10) % width
                y = (i * 29 + 18) % height
                draw.ellipse((x, y, x + 14, y + 5), fill=add_alpha((132, 204, 22, 255), 70))
        for y in range(0, height, 8):
            for x in range((y // 8) % 2 * 4, width, 16):
                draw.rectangle((x, y, x + 2, y + 2), fill=add_alpha(accent, 160))
        for i in range(26):
            x = (i * 37 + 13) % width
            y = (i * 53 + 9) % height
            draw.line((x, y, x + 5, y + 2), fill=shade(accent, 28), width=1)
    elif "tree" in key:
        draw.ellipse((22, 32, 76, 88), fill=(30, 83, 54, 255), outline=(12, 50, 34, 255))
        draw.ellipse((38, 12, 92, 70), fill=(45, 111, 70, 255), outline=(12, 50, 34, 255))
        draw.rectangle((44, 64, 58, 95), fill=(99, 61, 38, 255))
        draw.arc((28, 36, 70, 78), 205, 330, fill=(134, 239, 172, 120), width=2)
        draw.arc((44, 16, 86, 58), 205, 330, fill=(134, 239, 172, 130), width=2)
    elif "rock" in key:
        draw.polygon([(18, 78), (33, 34), (72, 18), (91, 54), (74, 88), (34, 90)], fill=(101, 116, 130, 255), outline=(30, 41, 59, 255))
        draw.line((35, 38, 70, 20), fill=(203, 213, 225, 120), width=3)
    else:
        draw.rectangle((42, 20, 58, 78), fill=(148, 163, 184, 255), outline=(51, 65, 85, 255))
        draw.rectangle((25, 20, 75, 34), fill=(148, 163, 184, 255), outline=(51, 65, 85, 255))
        draw.ellipse((20, 76, 80, 94), fill=(0, 0, 0, 75))
        draw.line((46, 26, 54, 70), fill=(226, 232, 240, 110), width=2)
    return add_pixel_polish(image)


def render_map_mechanic_asset(asset: Asset) -> Image.Image:
    width, height = image_size_for(asset)
    image = transparent_canvas(width, height)
    draw = ImageDraw.Draw(image, "RGBA")
    key = asset.key
    if "minimap" in key:
        color = mechanic_color(key)
        draw.ellipse((3, 3, width - 4, height - 4), fill=color, outline=(241, 245, 249, 220))
        return image
    if "river" in key:
        draw.rectangle((0, 0, width, height), fill=(26, 84, 126, 220))
        for y in range(18, height, 32):
            draw.arc((10, y - 16, width - 10, y + 18), 0, 180, fill=(125, 211, 252, 120), width=3)
    elif "swamp" in key:
        draw.ellipse((12, 18, width - 12, height - 22), fill=(24, 95, 82, 225), outline=(74, 222, 128, 180), width=3)
        for i in range(10):
            draw.ellipse(((i * 29) % width, (i * 41) % height, (i * 29) % width + 7, (i * 41) % height + 7), fill=(190, 242, 100, 130))
    elif "mud" in key:
        draw.ellipse((18, 25, width - 18, height - 25), fill=(92, 64, 51, 230), outline=(161, 98, 7, 160), width=3)
        for i in range(18):
            draw.rectangle(((i * 19) % width, (i * 23) % height, (i * 19) % width + 4, (i * 23) % height + 2), fill=(120, 72, 44, 170))
    elif "portal" in key:
        color = mechanic_color(key)
        draw.ellipse((20, 12, width - 20, height - 12), outline=color, width=8)
        draw.ellipse((36, 28, width - 36, height - 28), outline=add_alpha(shade(color, 35), 180), width=5)
        draw.ellipse((width // 2 - 12, height // 2 - 12, width // 2 + 12, height // 2 + 12), fill=add_alpha(color, 180))
    elif "light" in key:
        draw.ellipse((18, 18, width - 18, height - 18), fill=(250, 204, 21, 70), outline=(250, 204, 21, 180), width=2)
        draw.rectangle((width // 2 - 8, height // 2, width // 2 + 8, height - 12), fill=(71, 85, 105, 255))
        draw.polygon([(width // 2, 16), (width // 2 - 14, height // 2), (width // 2 + 14, height // 2)], fill=(251, 191, 36, 255))
    elif "obstacle" in key:
        return render_world_asset(Asset(asset.path, asset.key, "image", width, height, 1, asset.raw))
    elif "hazard" in key:
        color = mechanic_color(key)
        for i in range(6):
            x = 18 + i * (width - 36) / 5
            draw.polygon([(x, height - 18), (x + 10, 34), (x + 20, height - 18)], fill=color, outline=(31, 41, 55, 255))
    elif "altar" in key:
        rounded(draw, (28, 45, width - 28, height - 24), 8, fill=(100, 116, 139, 255), outline=(30, 41, 59, 255))
        draw.ellipse((44, 18, width - 44, 56), fill=(250, 204, 21, 150), outline=(250, 204, 21, 255), width=3)
    elif "spawner" in key:
        draw.ellipse((22, 26, width - 22, height - 20), fill=(51, 65, 85, 255), outline=(147, 51, 234, 230), width=5)
        draw.ellipse((48, 50, width - 48, height - 44), fill=(168, 85, 247, 180))
    return add_pixel_polish(image)


def generate_tier_assets() -> list[Asset]:
    result: list[Asset] = []
    for weapon in WEAPON_IDS:
        for tier in (1, 2, 3):
            icon_path = f"weapons/{weapon}_icon_tier{tier}.png"
            icon_key = f"art_weapons_{weapon}_icon_tier{tier}"
            icon_asset = make_asset(icon_path, icon_key, "image", 64, 64, 1)
            image = transparent_canvas(64, 64)
            draw_weapon_symbol(image, weapon, tier, 0, False)
            save_asset(icon_asset, image)
            result.append(icon_asset)

            sheet_path = f"weapons/{weapon}_projectile_tier{tier}_sheet.png"
            sheet_key = f"art_weapons_{weapon}_projectile_tier{tier}_sheet"
            sheet_asset = make_asset(sheet_path, sheet_key, "spritesheet", 64, 64, 4)
            sheet = transparent_canvas(256, 64)
            for frame in range(4):
                cell = transparent_canvas(64, 64)
                draw_weapon_symbol(cell, weapon, tier, frame, True)
                sheet.alpha_composite(cell, (frame * 64, 0))
            save_asset(sheet_asset, sheet)
            result.append(sheet_asset)

    for passive in PASSIVE_IDS:
        for tier in (1, 2, 3):
            path = f"passives/{passive}_icon_tier{tier}.png"
            key = f"art_passives_{passive}_icon_tier{tier}"
            asset = make_asset(path, key, "image", 64, 64, 1)
            image = transparent_canvas(64, 64)
            draw_passive_symbol(image, passive, tier)
            save_asset(asset, image)
            result.append(asset)

    return result


def make_asset(path: str, key: str, kind: str, fw: int, fh: int, frames: int) -> Asset:
    raw = {"path": path, "key": key, "type": kind, "frameWidth": fw, "frameHeight": fh, "frames": frames}
    return parse_asset(raw)


def save_asset(asset: Asset, image: Image.Image) -> None:
    path = ART_ROOT / asset.path
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def draw_weapon_symbol(image: Image.Image, weapon: str, tier: int, frame: int, animated: bool) -> None:
    draw = ImageDraw.Draw(image, "RGBA")
    w, h = image.size
    accent = weapon_color(weapon, tier)
    draw_tier_backplate(draw, w, h, accent, tier, frame if animated else 0)
    rot = frame * 10 if animated else 0

    if "knife" in weapon or "thousand_edge" in weapon:
        blade = [(w * 0.22, h * 0.70), (w * 0.72, h * 0.20), (w * 0.82, h * 0.30), (w * 0.34, h * 0.80)]
        draw.polygon(rotate_points(blade, w / 2, h / 2, rot), fill=(226, 232, 240, 255), outline=(51, 65, 85, 255))
        draw.rectangle((w * 0.22, h * 0.68, w * 0.42, h * 0.78), fill=accent)
        if tier >= 2:
            draw.line((w * 0.36, h * 0.60, w * 0.68, h * 0.26), fill=add_alpha(accent, 230), width=2)
        if tier >= 3:
            draw.line((w * 0.28, h * 0.76, w * 0.77, h * 0.27), fill=(255, 255, 255, 210), width=1)
            draw.polygon([(w * 0.71, h * 0.18), (w * 0.86, h * 0.21), (w * 0.80, h * 0.34)], fill=shade(accent, 45), outline=(240, 249, 255, 180))
    elif "garlic" in weapon or "soul_eater" in weapon:
        for i in range(6 + tier):
            angle = math.tau * i / (6 + tier) + frame * 0.25
            x = w / 2 + math.cos(angle) * (13 + tier * 2)
            y = h / 2 + math.sin(angle) * (13 + tier * 2)
            draw.ellipse((x - 7, y - 7, x + 7, y + 7), fill=shade(accent, 10), outline=(31, 41, 55, 255))
        draw.ellipse((w / 2 - 13, h / 2 - 13, w / 2 + 13, h / 2 + 13), fill=(242, 232, 196, 255), outline=accent, width=2 + tier)
        if tier >= 3:
            draw.ellipse((w / 2 - 23, h / 2 - 23, w / 2 + 23, h / 2 + 23), outline=add_alpha(shade(accent, 55), 210), width=2)
    elif "bible" in weapon or "vespers" in weapon:
        rounded(draw, (17, 14, 47, 51), 4, fill=(88, 28, 135, 255), outline=(31, 41, 55, 255))
        draw.rectangle((21, 18, 43, 48), fill=shade(accent, -12))
        draw.rectangle((30, 20, 34, 46), fill=(250, 204, 21, 255))
        draw.rectangle((25, 30, 39, 34), fill=(250, 204, 21, 255))
        if tier >= 2:
            draw.arc((13, 10, 51, 55), 210, 330, fill=add_alpha((255, 255, 255, 255), 130), width=2)
        if tier >= 3:
            for y in (22, 38):
                draw.line((22, y, 42, y + 3), fill=add_alpha((255, 255, 255, 255), 120), width=1)
    elif "wand" in weapon:
        draw.line((20, 50, 45, 16), fill=(120, 53, 15, 255), width=5)
        draw.line((22, 48, 47, 14), fill=(250, 204, 21, 255), width=2)
        star(draw, 47, 14, 12 + tier * 2, fill=accent, outline=(240, 249, 255, 255))
        if tier >= 3:
            star(draw, 24, 26, 5, fill=add_alpha(shade(accent, 40), 220), outline=add_alpha((255, 255, 255, 255), 150))
    elif "axe" in weapon or "spiral" in weapon:
        draw.line((21, 52, 42, 15), fill=(120, 53, 15, 255), width=5)
        draw.pieslice((29, 7, 59, 37), 270, 90, fill=(226, 232, 240, 255), outline=(51, 65, 85, 255))
        draw.pieslice((18, 10, 48, 40), 90, 270, fill=shade(accent, 12), outline=(51, 65, 85, 255))
        if tier >= 3:
            draw.arc((8, 8, 56, 56), 25, 190, fill=add_alpha(shade(accent, 55), 190), width=3)
    else:
        star(draw, w / 2, h / 2, 20 + tier * 3, fill=accent, outline=(240, 249, 255, 255))

    if tier >= 3:
        for i in range(6):
            a = math.tau * i / 6 + frame * 0.18
            x = w / 2 + math.cos(a) * 25
            y = h / 2 + math.sin(a) * 25
            draw.rectangle((x - 1, y - 1, x + 1, y + 1), fill=(255, 255, 255, 220))
        draw.ellipse((8, 8, w - 8, h - 8), outline=add_alpha(shade(accent, 60), 150), width=2)
    if tier >= 2:
        for i in range(4):
            a = math.tau * i / 4 + frame * 0.35
            x = w / 2 + math.cos(a) * (19 + tier * 2)
            y = h / 2 + math.sin(a) * (19 + tier * 2)
            draw.line((w / 2, h / 2, x, y), fill=add_alpha(accent, 35 + tier * 18), width=1)


def draw_tier_backplate(
    draw: ImageDraw.ImageDraw,
    width: int,
    height: int,
    color: tuple[int, int, int, int],
    tier: int,
    frame: int,
) -> None:
    glow = 28 + tier * 46
    draw.ellipse((5, 5, width - 5, height - 5), fill=add_alpha(color, glow), outline=add_alpha(shade(color, 40), 80 + tier * 35), width=max(1, tier))
    if tier >= 2:
        diamond = [
            (width / 2, 4),
            (width - 6, height / 2),
            (width / 2, height - 6),
            (6, height / 2),
        ]
        draw.polygon(diamond, outline=add_alpha(shade(color, 65), 150))
        for i in range(4):
            angle = math.tau * i / 4 + frame * 0.16
            x = width / 2 + math.cos(angle) * 25
            y = height / 2 + math.sin(angle) * 25
            draw.rectangle((x - 2, y - 2, x + 2, y + 2), fill=add_alpha(shade(color, 50), 160))
    if tier >= 3:
        for i in range(8):
            angle = math.tau * i / 8 + frame * 0.12
            inner = 22
            outer = 30
            draw.line(
                (
                    width / 2 + math.cos(angle) * inner,
                    height / 2 + math.sin(angle) * inner,
                    width / 2 + math.cos(angle) * outer,
                    height / 2 + math.sin(angle) * outer,
                ),
                fill=add_alpha(shade(color, 80), 190),
                width=2,
            )


def draw_passive_symbol(image: Image.Image, passive: str, tier: int) -> None:
    draw = ImageDraw.Draw(image, "RGBA")
    w, h = image.size
    accent = passive_color(passive, tier)
    draw_icon_frame(draw, w, h, accent, tier)
    if passive == "spinach":
        draw.ellipse((21, 18, 46, 49), fill=(34, 197, 94, 255), outline=(20, 83, 45, 255))
        draw.line((30, 45, 43, 20), fill=(187, 247, 208, 210), width=2)
    elif passive == "empty_tome":
        rounded(draw, (18, 15, 48, 52), 3, fill=(245, 222, 179, 255), outline=(92, 64, 51, 255))
        draw.line((33, 17, 33, 50), fill=(120, 113, 108, 255), width=2)
        for y in range(24, 46, 7):
            draw.line((22, y, 30, y), fill=(91, 33, 182, 180), width=1)
            draw.line((36, y, 45, y), fill=(91, 33, 182, 180), width=1)
    elif passive == "bracer":
        draw.ellipse((15, 20, 50, 50), outline=(250, 204, 21, 255), width=7)
        draw.rectangle((27, 16, 38, 24), fill=accent)
    elif passive == "clover":
        for dx, dy in [(-8, -8), (8, -8), (-8, 8), (8, 8)]:
            draw.ellipse((32 + dx - 8, 32 + dy - 8, 32 + dx + 8, 32 + dy + 8), fill=(34, 197, 94, 255), outline=(20, 83, 45, 255))
        draw.line((32, 36, 25, 52), fill=(21, 128, 61, 255), width=3)
    else:
        draw.ellipse((18, 17, 46, 45), fill=(239, 68, 68, 255), outline=(127, 29, 29, 255))
        draw.rectangle((29, 25, 35, 50), fill=(244, 114, 182, 255))
    if tier >= 2:
        draw.ellipse((8, 8, w - 8, h - 8), outline=add_alpha(accent, 170), width=tier)
        draw_tier_corner_gems(draw, w, h, accent, tier)
    if tier >= 3:
        star(draw, w - 14, 14, 5, fill=add_alpha(shade(accent, 55), 230), outline=add_alpha((255, 255, 255, 255), 150))


def draw_enemy(image: Image.Image, enemy: str, frame: int) -> None:
    draw = ImageDraw.Draw(image, "RGBA")
    w, h = image.size
    bob = [0, -2, 0, 2][frame % 4]
    draw.ellipse((w * 0.20, h * 0.74, w * 0.80, h * 0.91), fill=(0, 0, 0, 70))
    if "boss" in enemy or "lava" in enemy:
        body = (126, 34, 42, 255)
        accent = (251, 146, 60, 255)
        rounded(draw, (w * 0.20, h * 0.18 + bob, w * 0.80, h * 0.78 + bob), 18, fill=body, outline=(47, 24, 18, 255))
        for i in range(5):
            x = w * (0.26 + i * 0.12)
            draw.polygon([(x, h * 0.20 + bob), (x + 10, h * 0.04 + bob), (x + 20, h * 0.22 + bob)], fill=accent, outline=(47, 24, 18, 255))
        draw.rectangle((w * 0.33, h * 0.44 + bob, w * 0.43, h * 0.51 + bob), fill=(255, 247, 237, 255))
        draw.rectangle((w * 0.57, h * 0.44 + bob, w * 0.67, h * 0.51 + bob), fill=(255, 247, 237, 255))
        draw.line((w * 0.28, h * 0.62 + bob, w * 0.72, h * 0.64 + bob), fill=(69, 10, 10, 255), width=max(2, int(w * 0.025)))
        for i in range(4):
            x = w * (0.30 + i * 0.13)
            draw.line((x, h * 0.30 + bob, x + 8, h * 0.70 + bob), fill=add_alpha(accent, 140), width=2)
    elif "golem" in enemy:
        body = (100, 116, 139, 255)
        rounded(draw, (w * 0.18, h * 0.22 + bob, w * 0.82, h * 0.78 + bob), 8, fill=body, outline=(30, 41, 59, 255))
        draw.rectangle((w * 0.27, h * 0.34 + bob, w * 0.43, h * 0.43 + bob), fill=(125, 211, 252, 255))
        draw.rectangle((w * 0.57, h * 0.34 + bob, w * 0.73, h * 0.43 + bob), fill=(125, 211, 252, 255))
        draw.line((w * 0.32, h * 0.60 + bob, w * 0.68, h * 0.62 + bob), fill=(30, 41, 59, 255), width=3)
        for i in range(3):
            x = w * (0.26 + i * 0.18)
            draw.line((x, h * 0.25 + bob, x + 10, h * 0.76 + bob), fill=(203, 213, 225, 90), width=2)
    elif "bat" in enemy:
        body = (76, 29, 149, 255)
        draw.polygon([(w * 0.12, h * 0.48 + bob), (w * 0.33, h * 0.23 + bob), (w * 0.48, h * 0.50 + bob)], fill=shade(body, 15), outline=(30, 27, 75, 255))
        draw.polygon([(w * 0.88, h * 0.48 + bob), (w * 0.67, h * 0.23 + bob), (w * 0.52, h * 0.50 + bob)], fill=shade(body, 15), outline=(30, 27, 75, 255))
        draw.ellipse((w * 0.34, h * 0.30 + bob, w * 0.66, h * 0.63 + bob), fill=body, outline=(30, 27, 75, 255))
        draw.rectangle((w * 0.42, h * 0.42 + bob, w * 0.46, h * 0.46 + bob), fill=(248, 113, 113, 255))
        draw.rectangle((w * 0.54, h * 0.42 + bob, w * 0.58, h * 0.46 + bob), fill=(248, 113, 113, 255))
        draw.arc((w * 0.39, h * 0.50 + bob, w * 0.61, h * 0.66 + bob), 0, 180, fill=(248, 250, 252, 180), width=1)
    else:
        body = (74, 222, 128, 255)
        rounded(draw, (w * 0.16, h * 0.34 + bob, w * 0.84, h * 0.75 + bob), 16, fill=body, outline=(20, 83, 45, 255))
        draw.rectangle((w * 0.35, h * 0.48 + bob, w * 0.41, h * 0.54 + bob), fill=(22, 101, 52, 255))
        draw.rectangle((w * 0.59, h * 0.48 + bob, w * 0.65, h * 0.54 + bob), fill=(22, 101, 52, 255))
        draw.arc((w * 0.25, h * 0.36 + bob, w * 0.75, h * 0.62 + bob), 200, 340, fill=(187, 247, 208, 150), width=2)
        for i in range(3):
            x = w * (0.30 + i * 0.15)
            draw.ellipse((x, h * 0.30 + bob, x + 3, h * 0.34 + bob), fill=(220, 252, 231, 170))


def render_skill_effect(width: int, height: int, color: tuple[int, int, int, int], name: str) -> Image.Image:
    if "circle" in name or "zone" in name or "wave" in name:
        image = transparent_canvas(width, height)
        draw = ImageDraw.Draw(image, "RGBA")
        draw.ellipse((6, 6, width - 6, height - 6), outline=add_alpha(color, 180), width=4)
        draw.ellipse((width * 0.25, height * 0.25, width * 0.75, height * 0.75), fill=add_alpha(color, 45), outline=add_alpha(shade(color, 45), 130), width=2)
        return image
    return render_burst(width, height, color, rings=2)


def render_burst(width: int, height: int, color: tuple[int, int, int, int], rings: int, frame: int = 0) -> Image.Image:
    image = transparent_canvas(width, height)
    draw = ImageDraw.Draw(image, "RGBA")
    cx, cy = width / 2, height / 2
    max_radius = min(width, height) * (0.22 + 0.09 * frame)
    for ring in range(rings):
        radius = max_radius + ring * 7
        alpha = max(35, 220 - ring * 55 - frame * 24)
        draw.ellipse((cx - radius, cy - radius, cx + radius, cy + radius), outline=add_alpha(color, alpha), width=max(2, rings - ring))
    for i in range(8):
        angle = math.tau * i / 8 + frame * 0.15
        r1 = max_radius * 0.25
        r2 = max_radius * (0.85 + rings * 0.08)
        draw.line((cx + math.cos(angle) * r1, cy + math.sin(angle) * r1, cx + math.cos(angle) * r2, cy + math.sin(angle) * r2), fill=add_alpha(color, 170), width=2)
    for i in range(12):
        angle = math.tau * i / 12 + frame * 0.37
        radius = max_radius * (0.45 + (i % 3) * 0.22)
        x = cx + math.cos(angle) * radius
        y = cy + math.sin(angle) * radius
        draw.rectangle((x - 1, y - 1, x + 1, y + 1), fill=add_alpha(shade(color, 70), max(70, 220 - frame * 35)))
    return image


def render_warning(width: int, height: int, color: tuple[int, int, int, int]) -> Image.Image:
    image = transparent_canvas(width, height)
    draw = ImageDraw.Draw(image, "RGBA")
    rounded(draw, (2, 8, width - 3, height - 9), 12, fill=add_alpha(color, 80), outline=add_alpha(color, 220))
    for x in range(16, width, 32):
        draw.line((x, 12, x + 18, height - 12), fill=add_alpha(color, 130), width=5)
    return image


def draw_icon_frame(draw: ImageDraw.ImageDraw, width: int, height: int, color: tuple[int, int, int, int], tier: int) -> None:
    fill = (15, 23, 42, 210) if tier == 1 else (12, 18, 36, 232)
    rounded(draw, (3, 3, width - 4, height - 4), 8, fill=fill, outline=add_alpha(color, 120 + tier * 35))
    draw.rectangle((9, 8, width - 10, 12), fill=add_alpha(color, 60 + tier * 35))
    if tier >= 2:
        rounded(draw, (7, 7, width - 8, height - 8), 5, outline=add_alpha(shade(color, 55), 110 + tier * 32))
        draw.rectangle((7, height - 12, width - 8, height - 8), fill=add_alpha(color, 70 + tier * 30))
        draw.line((12, height - 18, width - 12, 16), fill=add_alpha((255, 255, 255, 255), 34 + tier * 12), width=1)
    if tier >= 3:
        for x in (11, width - 15):
            for y in (11, height - 15):
                draw.rectangle((x, y, x + 4, y + 4), fill=add_alpha(color, 220))
        draw.rectangle((width // 2 - 7, 4, width // 2 + 7, 8), fill=add_alpha(shade(color, 70), 210))
        draw.rectangle((width // 2 - 3, 1, width // 2 + 3, 6), fill=add_alpha((255, 255, 255, 255), 180))


def draw_tier_corner_gems(
    draw: ImageDraw.ImageDraw,
    width: int,
    height: int,
    color: tuple[int, int, int, int],
    tier: int,
) -> None:
    positions = [(12, 12), (width - 13, 12), (12, height - 13), (width - 13, height - 13)]
    for index, (x, y) in enumerate(positions):
        if tier == 2 and index in (1, 2):
            continue
        draw.polygon(
            [(x, y - 4), (x + 4, y), (x, y + 4), (x - 4, y)],
            fill=add_alpha(shade(color, 45), 210),
            outline=add_alpha((255, 255, 255, 255), 120),
        )


def render_review_sheets(review_dir: Path, assets: list[Asset]) -> None:
    review_dir.mkdir(parents=True, exist_ok=True)
    groups: dict[str, list[Asset]] = {}
    for asset in assets:
        groups.setdefault(asset.path.split("/")[0], []).append(asset)
    for group, group_assets in groups.items():
        thumbs: list[tuple[str, Image.Image]] = []
        for asset in group_assets[:80]:
            path = ART_ROOT / asset.path
            if not path.exists():
                continue
            with Image.open(path) as image:
                thumb = image.convert("RGBA")
                thumb.thumbnail((96, 96), Image.Resampling.NEAREST)
                canvas = Image.new("RGBA", (120, 128), (15, 23, 42, 255))
                canvas.alpha_composite(thumb, ((120 - thumb.width) // 2, 6))
                label = asset.key.replace("art_", "")[-24:]
                draw = ImageDraw.Draw(canvas)
                draw.text((4, 104), label, fill=(226, 232, 240, 255), font=small_font())
                thumbs.append((asset.key, canvas))
        if not thumbs:
            continue
        columns = 6
        rows = math.ceil(len(thumbs) / columns)
        sheet = Image.new("RGBA", (columns * 120, rows * 128), (2, 6, 23, 255))
        for index, (_, thumb) in enumerate(thumbs):
            sheet.alpha_composite(thumb, ((index % columns) * 120, (index // columns) * 128))
        sheet.save(review_dir / f"{group}_contact_sheet.png")


def render_tier_progression_review(review_dir: Path) -> None:
    cell_w = 104
    cell_h = 116
    rows = len(WEAPON_IDS) + len(PASSIVE_IDS)
    columns = 4
    sheet = Image.new("RGBA", (columns * cell_w, rows * cell_h), (2, 6, 23, 255))
    items = [("weapon", weapon) for weapon in WEAPON_IDS] + [("passive", passive) for passive in PASSIVE_IDS]

    for row, (kind, item_id) in enumerate(items):
        label = Image.new("RGBA", (cell_w, cell_h), (15, 23, 42, 255))
        draw = ImageDraw.Draw(label)
        draw.text((6, 10), kind, fill=(148, 163, 184, 255), font=small_font())
        draw.text((6, 28), item_id[:14], fill=(226, 232, 240, 255), font=small_font())
        sheet.alpha_composite(label, (0, row * cell_h))

        for tier in (1, 2, 3):
            path = ART_ROOT / (
                f"weapons/{item_id}_icon_tier{tier}.png"
                if kind == "weapon"
                else f"passives/{item_id}_icon_tier{tier}.png"
            )
            cell = Image.new("RGBA", (cell_w, cell_h), (15, 23, 42, 255))
            cell_draw = ImageDraw.Draw(cell)
            cell_draw.text((6, 6), f"tier {tier}", fill=(226, 232, 240, 255), font=small_font())
            if path.exists():
                with Image.open(path) as image:
                    thumb = image.convert("RGBA")
                    thumb.thumbnail((80, 80), Image.Resampling.NEAREST)
                    cell.alpha_composite(thumb, ((cell_w - thumb.width) // 2, 26))
            sheet.alpha_composite(cell, (tier * cell_w, row * cell_h))

    sheet.save(review_dir / "tier_progression_contact_sheet.png")


def transparent_canvas(width: int, height: int) -> Image.Image:
    return Image.new("RGBA", (width, height), (0, 0, 0, 0))


def add_pixel_polish(image: Image.Image) -> Image.Image:
    image = image.convert("RGBA")
    glow = Image.new("RGBA", image.size, (0, 0, 0, 0))
    alpha = image.getchannel("A")
    glow.putalpha(alpha.filter(ImageFilter.MaxFilter(3)).filter(ImageFilter.GaussianBlur(1.0)))
    tint = Image.new("RGBA", image.size, (125, 211, 252, 22))
    glow = Image.alpha_composite(glow, tint)
    out = Image.alpha_composite(glow, image)
    return out


def rounded(draw: ImageDraw.ImageDraw, box: tuple[float, float, float, float], radius: int, fill=None, outline=None) -> None:
    draw.rounded_rectangle(tuple(int(v) for v in box), radius=radius, fill=fill, outline=outline)


def add_highlight(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], color: tuple[int, int, int, int]) -> None:
    x1, y1, x2, y2 = box
    draw.line((x1 + 2, y1 + 2, x2 - 3, y1 + 2), fill=add_alpha(shade(color, 50), 120), width=2)


def add_sprite_sparkle(
    draw: ImageDraw.ImageDraw,
    x: float,
    y: float,
    color: tuple[int, int, int, int],
    frame: int,
) -> None:
    if frame % 2 != 0:
        return

    draw.rectangle((x - 1, y - 3, x + 1, y + 3), fill=add_alpha(shade(color, 65), 130))
    draw.rectangle((x - 3, y - 1, x + 3, y + 1), fill=add_alpha(shade(color, 65), 130))


def star(draw: ImageDraw.ImageDraw, cx: float, cy: float, radius: float, fill, outline=None) -> None:
    points = []
    for i in range(10):
        angle = -math.pi / 2 + i * math.pi / 5
        r = radius if i % 2 == 0 else radius * 0.42
        points.append((cx + math.cos(angle) * r, cy + math.sin(angle) * r))
    draw.polygon(points, fill=fill, outline=outline)


def rotate_points(points: list[tuple[float, float]], cx: float, cy: float, degrees: float) -> list[tuple[float, float]]:
    angle = math.radians(degrees)
    result = []
    for x, y in points:
        dx, dy = x - cx, y - cy
        result.append((cx + dx * math.cos(angle) - dy * math.sin(angle), cy + dx * math.sin(angle) + dy * math.cos(angle)))
    return result


def shade(color: tuple[int, int, int, int], amount: int) -> tuple[int, int, int, int]:
    return (
        max(0, min(255, color[0] + amount)),
        max(0, min(255, color[1] + amount)),
        max(0, min(255, color[2] + amount)),
        color[3],
    )


def add_alpha(color: tuple[int, int, int, int], alpha: int) -> tuple[int, int, int, int]:
    return (color[0], color[1], color[2], max(0, min(255, alpha)))


def weapon_color(weapon: str, tier: int) -> tuple[int, int, int, int]:
    base = {
        "knife": (148, 163, 184, 255),
        "thousand_edge": (125, 211, 252, 255),
        "garlic": (236, 222, 176, 255),
        "soul_eater": (168, 85, 247, 255),
        "bible": (96, 165, 250, 255),
        "unholy_vespers": (192, 132, 252, 255),
        "magic_wand": (56, 189, 248, 255),
        "holy_wand": (250, 204, 21, 255),
        "axe": (248, 113, 113, 255),
        "death_spiral": (251, 146, 60, 255),
    }.get(weapon, (148, 163, 184, 255))
    return shade(base, (tier - 1) * 28)


def passive_color(passive: str, tier: int) -> tuple[int, int, int, int]:
    base = {
        "spinach": (34, 197, 94, 255),
        "empty_tome": (129, 140, 248, 255),
        "bracer": (250, 204, 21, 255),
        "clover": (74, 222, 128, 255),
        "pummarola": (244, 114, 182, 255),
    }.get(passive, (148, 163, 184, 255))
    return shade(base, (tier - 1) * 24)


def effect_color(key: str) -> tuple[int, int, int, int]:
    if "boss" in key:
        return (248, 113, 113, 255)
    if "level" in key:
        return (250, 204, 21, 255)
    return (125, 211, 252, 255)


def mechanic_color(key: str) -> tuple[int, int, int, int]:
    if "gold" in key or "cathedral" in key or "altar" in key:
        return (250, 204, 21, 255)
    if "purple" in key:
        return (168, 85, 247, 255)
    if "green" in key or "swamp" in key:
        return (34, 197, 94, 255)
    if "hazard" in key or "fire" in key:
        return (248, 113, 113, 255)
    return (56, 189, 248, 255)


def weapon_from_key(key: str, path: str) -> str:
    source = f"{key}_{path}"
    for weapon in sorted(WEAPON_IDS, key=len, reverse=True):
        if weapon in source:
            return weapon
    return "knife"


def passive_from_key(key: str, path: str) -> str:
    source = f"{key}_{path}"
    for passive in PASSIVE_IDS:
        if passive in source:
            return passive
    return "spinach"


def enemy_from_key(key: str, path: str) -> str:
    source = f"{key}_{path}"
    if "lava" in source or "boss" in source:
        return "boss"
    if "bat" in source:
        return "bat"
    if "golem" in source:
        return "golem"
    return "slime"


def small_font() -> ImageFont.ImageFont:
    return ImageFont.load_default()


if __name__ == "__main__":
    main()
