import type { AudioAsset } from './AssetManifestTypes';

export const AUDIO_ASSETS: AudioAsset[] = [
  { key: 'enemy_hit', path: 'assets/audio/enemy_hit.wav' },
  { key: 'enemy_killed', path: 'assets/audio/enemy_killed.wav' },
  { key: 'player_hit', path: 'assets/audio/player_hit.wav' },
  { key: 'level_up', path: 'assets/audio/level_up.wav' },
  { key: 'upgrade_selected', path: 'assets/audio/upgrade_selected.wav' },
  { key: 'treasure_open', path: 'assets/audio/treasure_open.wav' },
  { key: 'boss_spawn', path: 'assets/audio/boss_spawn.wav' },
  { key: 'boss_dash', path: 'assets/audio/boss_dash.wav' },
  { key: 'victory', path: 'assets/audio/victory.wav' },
  { key: 'game_over', path: 'assets/audio/game_over.wav' },
  { key: 'ui_click', path: 'assets/audio/ui_click.wav' },
  { key: 'title_bgm', path: 'assets/audio/bgm/title_bgm.wav' },
  { key: 'gameplay_bgm', path: 'assets/audio/bgm/gameplay_bgm.wav' },
  { key: 'boss_bgm', path: 'assets/audio/bgm/boss_bgm.wav' },
  { key: 'result_bgm', path: 'assets/audio/bgm/result_bgm.wav' },
  { key: 'knife_attack', path: 'assets/audio/weapon/knife_attack.wav' },
  { key: 'axe_throw', path: 'assets/audio/weapon/axe_throw.wav' },
  { key: 'magic_wand_shot', path: 'assets/audio/weapon/magic_wand_shot.wav' },
  { key: 'bible_orbit_hit', path: 'assets/audio/weapon/bible_orbit_hit.wav' },
  { key: 'garlic_aura_tick', path: 'assets/audio/weapon/garlic_aura_tick.wav' },
  { key: 'thousand_edge_attack', path: 'assets/audio/weapon/thousand_edge_attack.wav' },
  { key: 'holy_wand_shot', path: 'assets/audio/weapon/holy_wand_shot.wav' },
  { key: 'death_spiral_throw', path: 'assets/audio/weapon/death_spiral_throw.wav' },
  { key: 'unholy_vespers_hit', path: 'assets/audio/weapon/unholy_vespers_hit.wav' },
  { key: 'soul_eater_tick', path: 'assets/audio/weapon/soul_eater_tick.wav' },
  { key: 'ui_hover', path: 'assets/audio/ui/ui_hover.wav' },
  { key: 'ui_back', path: 'assets/audio/ui/ui_back.wav' },
  { key: 'ui_confirm', path: 'assets/audio/ui/ui_confirm.wav' },
];
