import type { ArtManifestAsset } from './AssetManifestTypes';

export const MAP_MECHANIC_ASSETS: ArtManifestAsset[] = [
  { path: 'map-mechanics/river/river_tile.png', key: 'art_map_mechanics_river_tile', type: 'image', frameWidth: 256, frameHeight: 256, frames: 1 },
  { path: 'map-mechanics/river/river_bank.png', key: 'art_map_mechanics_river_bank', type: 'image', frameWidth: 256, frameHeight: 256, frames: 1 },
  { path: 'map-mechanics/river/river_ripple.png', key: 'art_map_mechanics_river_ripple', type: 'image', frameWidth: 128, frameHeight: 64, frames: 1 },
  { path: 'map-mechanics/river/river_minimap.png', key: 'art_map_mechanics_river_minimap', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/swamp/swamp_pool.png', key: 'art_map_mechanics_swamp_pool', type: 'image', frameWidth: 256, frameHeight: 256, frames: 1 },
  { path: 'map-mechanics/swamp/swamp_bubble.png', key: 'art_map_mechanics_swamp_bubble', type: 'image', frameWidth: 64, frameHeight: 64, frames: 1 },
  { path: 'map-mechanics/swamp/swamp_minimap.png', key: 'art_map_mechanics_swamp_minimap', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/mud/mud_patch.png', key: 'art_map_mechanics_mud_patch', type: 'image', frameWidth: 256, frameHeight: 256, frames: 1 },
  { path: 'map-mechanics/mud/mud_spot.png', key: 'art_map_mechanics_mud_spot', type: 'image', frameWidth: 64, frameHeight: 64, frames: 1 },
  { path: 'map-mechanics/mud/mud_minimap.png', key: 'art_map_mechanics_mud_minimap', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/portal/portal_blue.png', key: 'art_map_mechanics_portal_blue', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/portal/portal_purple.png', key: 'art_map_mechanics_portal_purple', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/portal/portal_green.png', key: 'art_map_mechanics_portal_green', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/portal/portal_minimap_blue.png', key: 'art_map_mechanics_portal_minimap_blue', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/portal/portal_minimap_purple.png', key: 'art_map_mechanics_portal_minimap_purple', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/portal/portal_minimap_green.png', key: 'art_map_mechanics_portal_minimap_green', type: 'image', frameWidth: 32, frameHeight: 32, frames: 1 },
  { path: 'map-mechanics/light/lamp.png', key: 'art_map_mechanics_light_lamp', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/light/torch.png', key: 'art_map_mechanics_light_torch', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/light/crystal.png', key: 'art_map_mechanics_light_crystal', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/light/light_minimap.png', key: 'art_map_mechanics_light_minimap', type: 'image', frameWidth: 24, frameHeight: 24, frames: 1 },
  { path: 'map-mechanics/obstacle/obstacle_tree.png', key: 'art_map_mechanics_obstacle_tree', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/obstacle/obstacle_rock.png', key: 'art_map_mechanics_obstacle_rock', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/obstacle/obstacle_grave.png', key: 'art_map_mechanics_obstacle_grave', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/obstacle/obstacle_wall.png', key: 'art_map_mechanics_obstacle_wall', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/obstacle/obstacle_minimap.png', key: 'art_map_mechanics_obstacle_minimap', type: 'image', frameWidth: 24, frameHeight: 24, frames: 1 },
  { path: 'map-mechanics/hazard/hazard_spike.png', key: 'art_map_mechanics_hazard_spike', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/hazard/hazard_fire.png', key: 'art_map_mechanics_hazard_fire', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/hazard/hazard_poison.png', key: 'art_map_mechanics_hazard_poison', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/hazard/hazard_minimap.png', key: 'art_map_mechanics_hazard_minimap', type: 'image', frameWidth: 24, frameHeight: 24, frames: 1 },
  { path: 'map-mechanics/altar/altar_basic.png', key: 'art_map_mechanics_altar_basic', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/altar/altar_minimap.png', key: 'art_map_mechanics_altar_minimap', type: 'image', frameWidth: 24, frameHeight: 24, frames: 1 },
  { path: 'map-mechanics/spawner/spawner_nest.png', key: 'art_map_mechanics_spawner_nest', type: 'image', frameWidth: 128, frameHeight: 128, frames: 1 },
  { path: 'map-mechanics/spawner/spawner_minimap.png', key: 'art_map_mechanics_spawner_minimap', type: 'image', frameWidth: 24, frameHeight: 24, frames: 1 },
];
