import type { AutoStrategyProfile } from './AutoStrategyProfile';
import { DEFAULT_AUTO_STRATEGY_PROFILE, PLAYTEST_AUTO_STRATEGY_PROFILE } from './AutoStrategyDefaults';

export const BUILT_IN_AUTO_STRATEGY_PROFILES: readonly AutoStrategyProfile[] = [
  DEFAULT_AUTO_STRATEGY_PROFILE,
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'survival_first',
    name: 'Survival First',
    movement: {
      survivalBias: 95,
      combatBias: 35,
      farmBias: 35,
      treasureBias: 20,
      bossBias: 35,
      riskTolerance: 15,
      loopBias: 70,
      overKitePenalty: 35,
    },
    upgrade: {
      evolutionPriority: 65,
      mainWeaponPriority: 45,
      newWeaponPriority: 25,
      passivePriority: 65,
      survivalPriority: 95,
      cooldownPriority: 70,
      damagePriority: 35,
      growthPriority: 40,
    },
    treasure: {
      openRiskTolerance: 20,
      evolutionChestPriority: 60,
      relicExpectedValuePriority: 35,
      routeDeviationTolerance: 25,
    },
    relic: {
      rarityPriority: 45,
      synergyPriority: 55,
      survivalRelicPriority: 90,
      damageRelicPriority: 35,
      economyRelicPriority: 25,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'fast_farm',
    name: 'Fast Farm',
    movement: {
      survivalBias: 55,
      combatBias: 45,
      farmBias: 95,
      treasureBias: 45,
      bossBias: 35,
      riskTolerance: 50,
      loopBias: 45,
      overKitePenalty: 65,
    },
    upgrade: {
      evolutionPriority: 70,
      mainWeaponPriority: 55,
      newWeaponPriority: 45,
      passivePriority: 55,
      survivalPriority: 35,
      cooldownPriority: 60,
      damagePriority: 55,
      growthPriority: 90,
    },
    treasure: {
      openRiskTolerance: 45,
      evolutionChestPriority: 65,
      relicExpectedValuePriority: 45,
      routeDeviationTolerance: 60,
    },
    relic: {
      rarityPriority: 45,
      synergyPriority: 60,
      survivalRelicPriority: 35,
      damageRelicPriority: 45,
      economyRelicPriority: 85,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'evolution_rush',
    name: 'Evolution Rush',
    movement: {
      survivalBias: 60,
      combatBias: 55,
      farmBias: 70,
      treasureBias: 60,
      bossBias: 50,
      riskTolerance: 45,
      loopBias: 55,
      overKitePenalty: 55,
    },
    upgrade: {
      evolutionPriority: 100,
      mainWeaponPriority: 85,
      newWeaponPriority: 25,
      passivePriority: 75,
      survivalPriority: 45,
      cooldownPriority: 65,
      damagePriority: 55,
      growthPriority: 55,
    },
    treasure: {
      openRiskTolerance: 50,
      evolutionChestPriority: 100,
      relicExpectedValuePriority: 45,
      routeDeviationTolerance: 55,
    },
    relic: {
      rarityPriority: 45,
      synergyPriority: 80,
      survivalRelicPriority: 40,
      damageRelicPriority: 60,
      economyRelicPriority: 45,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'treasure_greedy',
    name: 'Treasure Greedy',
    movement: {
      survivalBias: 45,
      combatBias: 45,
      farmBias: 50,
      treasureBias: 100,
      bossBias: 45,
      riskTolerance: 70,
      loopBias: 35,
      overKitePenalty: 70,
    },
    upgrade: {
      evolutionPriority: 75,
      mainWeaponPriority: 55,
      newWeaponPriority: 55,
      passivePriority: 45,
      survivalPriority: 35,
      cooldownPriority: 55,
      damagePriority: 70,
      growthPriority: 60,
    },
    treasure: {
      openRiskTolerance: 80,
      evolutionChestPriority: 85,
      relicExpectedValuePriority: 85,
      routeDeviationTolerance: 90,
    },
    relic: {
      rarityPriority: 80,
      synergyPriority: 70,
      survivalRelicPriority: 35,
      damageRelicPriority: 60,
      economyRelicPriority: 75,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'boss_hunter',
    name: 'Boss Hunter',
    movement: {
      survivalBias: 60,
      combatBias: 85,
      farmBias: 40,
      treasureBias: 45,
      bossBias: 100,
      riskTolerance: 60,
      loopBias: 45,
      overKitePenalty: 60,
    },
    upgrade: {
      evolutionPriority: 80,
      mainWeaponPriority: 80,
      newWeaponPriority: 35,
      passivePriority: 40,
      survivalPriority: 45,
      cooldownPriority: 75,
      damagePriority: 95,
      growthPriority: 35,
    },
    treasure: {
      openRiskTolerance: 55,
      evolutionChestPriority: 80,
      relicExpectedValuePriority: 65,
      routeDeviationTolerance: 45,
    },
    relic: {
      rarityPriority: 55,
      synergyPriority: 80,
      survivalRelicPriority: 40,
      damageRelicPriority: 95,
      economyRelicPriority: 30,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'endless_safe',
    name: 'Endless Safe',
    movement: {
      survivalBias: 90,
      combatBias: 55,
      farmBias: 45,
      treasureBias: 35,
      bossBias: 60,
      riskTolerance: 20,
      loopBias: 85,
      overKitePenalty: 30,
    },
    upgrade: {
      evolutionPriority: 75,
      mainWeaponPriority: 60,
      newWeaponPriority: 25,
      passivePriority: 75,
      survivalPriority: 90,
      cooldownPriority: 80,
      damagePriority: 55,
      growthPriority: 70,
    },
    treasure: {
      openRiskTolerance: 30,
      evolutionChestPriority: 75,
      relicExpectedValuePriority: 60,
      routeDeviationTolerance: 35,
    },
    relic: {
      rarityPriority: 60,
      synergyPriority: 75,
      survivalRelicPriority: 95,
      damageRelicPriority: 55,
      economyRelicPriority: 45,
    },
  },
  {
    ...DEFAULT_AUTO_STRATEGY_PROFILE,
    id: 'glass_cannon',
    name: 'Glass Cannon',
    movement: {
      survivalBias: 35,
      combatBias: 95,
      farmBias: 60,
      treasureBias: 55,
      bossBias: 85,
      riskTolerance: 85,
      loopBias: 25,
      overKitePenalty: 85,
    },
    upgrade: {
      evolutionPriority: 80,
      mainWeaponPriority: 85,
      newWeaponPriority: 55,
      passivePriority: 30,
      survivalPriority: 20,
      cooldownPriority: 80,
      damagePriority: 100,
      growthPriority: 45,
    },
    treasure: {
      openRiskTolerance: 75,
      evolutionChestPriority: 85,
      relicExpectedValuePriority: 70,
      routeDeviationTolerance: 65,
    },
    relic: {
      rarityPriority: 65,
      synergyPriority: 80,
      survivalRelicPriority: 20,
      damageRelicPriority: 100,
      economyRelicPriority: 35,
    },
  },
];

export const INTERNAL_AUTO_STRATEGY_PROFILES: readonly AutoStrategyProfile[] = [
  PLAYTEST_AUTO_STRATEGY_PROFILE,
];

